### ISSUE TITLE
On Windows, execution fails in calls to CPT - Fortran compiler problem?

### ISSUE THREAD

**Issue by awrobertson** [iri-pycpt/iri-pycpt.github.io#13]
I looked into this last fall and here are my notes, including some emails with Kyle.

---

Nov 16, 2022

M1 Windows
- failing in PFV; that's what I found below in Oct
<img width="776" alt="Screenshot 2022-11-16 at 18 30 18" src="https://user-images.githubusercontent.com/21113530/213712649-1f419705-65ae-40ea-a020-e2ee2d839a6f.png">

- Lenovo: fails on 2nd CCA call:
	- cca_h, cca_f, cca_s, cca_px, cca_py = cc.canonical_correlation_analysis(model_hcst, Y, F=ce.redate(model_hcst), **cpt_args)
But same place, just after having translated the X dataset xarray into tsv format
```
cpt.write( max(X.coords[x_lat_dim].values)) # North
```

# Load X dataset 
    to_cptv10(X, cpt.outputs['original_predictor'], row=x_lat_dim, col=x_lon_dim, T=x_sample_dim)
    cpt.write(1)
    cpt.write(cpt.outputs['original_predictor'].absolute())
    if len(X.coords) >= 3: # then this is gridded data
        cpt.write( max(X.coords[x_lat_dim].values)) # North

---

Oct 28, 2022

From: Kyle Hall <hallkjc01@gmail.com>
Subject: Re: Windows PyCPT2 problem
Date: October 28, 2022 at 17:21:56 EDT
To: Andrew Robertson <awr@iri.columbia.edu>
Cc: Jeff Turmelle <jefft@iri.columbia.edu>, Kyle Hall <kjhall@iri.columbia.edu>

In the windows CPT screenshot you sent, you see that the values of the field and season both start with “%ta” ?

That is a tab stop character. CPT should recognize that as part of the tab, in the tab-separated-values, and know that it is not part of the actual values of date or field. That will definitely be causing an error- can’t say whether it’s the only one. 

At the very least, it shouldn’t be printing it to the GUI

On Fri, Oct 28, 2022 at 5:15 PM Andrew Robertson <awr@iri.columbia.edu> wrote:
Hi Kyle,

The cross-validated probabilistic hindcasts generated by PyCPT2 running on Windows have the following daily date format: T=1982-6-1/1982-8-31, rather than 1982-06/08.  Is that what you’re expecting?  

cpt:nfields=1
cpt:ncats=3
cpt:field=probabilistic, cpt:T=1982-6-1/1982-8-31, cpt:C=1, cpt:clim_prob=0.33333, cpt:nrow=40, cpt:ncol=40, cpt:row=Y, cpt:col=X, cpt:units=probability (%), cpt:missing=-1.000000

I didn’t follow what you meant about the tab stops. 

Andy

On Oct 28, 2022, at 09:54, Kyle Hall <hallkjc01@gmail.com> wrote:

Or rather, to be clear, when python writes newlines and tabs it auto-detects the operating system and writes the appropriate character. So there's probably some version issue with the Windows fortran compiler or something like that. 

On Fri, Oct 28, 2022 at 8:53 AM Kyle Hall <hallkjc01@gmail.com> wrote:
It might be possible to write Python  to accommodate the broken fortran, but I don’t recommend it. It’s not the Python because the behavior is fine on mac and Linux.

On Fri, Oct 28, 2022 at 8:51 AM Kyle Hall <hallkjc01@gmail.com> wrote:
This is an issue with windows CPT’s treatment of tab stops - this might help Simon or Jeff resolve the issue. 

https://stackoverflow.com/questions/40418292/fortran-write-array-tab-delimited-to-text-file

On Thu, Oct 27, 2022 at 8:24 PM Jeff Turmelle <jefft@iri.columbia.edu> wrote:
	As an aside, I noticed that there is a log=none parameter when instantiating the CPT class.  Perhaps that would do what we want? Unfortunately, I don’t know where to find this yet.Jeff> On Oct 27, 2022, at 7:22 PM, Andrew Robertson <awr@iri.columbia.edu> wrote:> > Hi Kyle,> > I hope you're enjoying your new work - I guess you are planning to move to Boulder soon?> > I was talking to Jeff today about how we might debug the Windows CPT execution problem.> > I just reran one case on Windows and it actually failed in PFV. 
	
	So I wrote out the cca_h.probabilistic in .tsv, and tried to run that in Windows CPT. I noticed that the date format doesn’t match (2nd screenshot)  and thus it did not run. I know this isn’t the reason for the crash, but any thoughts on why the format is off? 
	
	> > My goal is to actually to step through the *batch version* in Windows. I don’t think this has been tested much bc no one ever runs the batch version on Windows - so am thinking this may be the source of our problems?

<img width="742" alt="Screenshot 2022-11-16 at 18 26 55" src="https://user-images.githubusercontent.com/21113530/213712805-abf1cc7b-8c22-4e44-8ae0-5f0bff3565bf.png">

---

Sept 26, 2022

From: Andrew Robertson <awr@iri.columbia.edu>
Subject: Re: PyCPT 2 Windows installation problems
Date: September 26, 2022 at 10:03:41 EDT
To: Kyle Hall <hallkjc01@gmail.com>
Cc: Simon Mason <simon@iri.columbia.edu>, Angel Munoz <agmunoz@iri.columbia.edu>, Bohar Singh <bohar@iri.columbia.edu>, Kyle Hall <kjhall@iri.columbia.edu>

Hi Kyle,

Simon is busy with teaching so he may not be able to respond. Is the current version the same as the one that you had previously tested under Windows, or has CPT been incremented since then? Is there a previous CPT version that we could use to get around this? 

Andy

On Sep 26, 2022, at 09:46, Kyle Hall <hallkjc01@gmail.com> wrote:

Hi Andy, bohar, 

These are CPT bugs. I have no idea what’s happening there - Simon, do you? 

I experienced similar issues with older versions of the CPT_batch.exe and CPT_batch_installer.exe, but they seemed to improve when I upgraded the windows CPT stuff to 17.7.6. 

I don’t have a windows computer to try to help you with, nor did I ever actually have one when I was at IRI. A bootcamped MacBook is a far cry from a real windows and it’s hard to tell whether the bugs are from that or from real issues. I can re-build CPT core for you if one of you is able to come up with a fully working CPT_batch_installation.exe version, but that’s about all I can do at this point. 

On Sun, Sep 25, 2022 at 2:38 PM Andrew Robertson <awr@iri.columbia.edu> wrote:
Hi Kyle,

Hope you are doing well!

I’m getting a CPT error when running on Windows. Installation went fine. 
I get the same error on 2 configurations:
1) Windows 11 under Parallels on my M1 Mac. I was expecting this might fail because of the ARM proc.
2) My wife’s PC running Windows 11 - not expecting this to fail (see config screenshot below).

Also, what is the minimum PC requirement (Windows version, processor age, RAM, hard drive storage) in order to install Anaconda & pycpt?
I’ve been testing it on very up-to-date with Windows 11. Are we going to run into problem with old machines?

We need to write to all the participants tomorrow and ask them to do the installations before they come. They are bandwidth heavy and might cause us problems at the hotel.

Best,
Andy

**Comment by aaron-kaplan** [comment]
I believe this was fixed with the first release of cpt-bin. Let me know if you hear of any more crashes.
