### ISSUE TITLE
Provide example of how to use local data

### ISSUE THREAD

**Issue by asherb18** [iri-pycpt/iri-pycpt.github.io#6]
What's the best way to make sure that users can access local data? Can we have documentation on that process in a public place - even if they might want to access some private data?

**Comment by kjhall01** [comment]
Asher- it is an option for you to manually prepare and use Niger/ANACIM ENACTS data with Xarray and CPT-IO. It is a matter of your knowing how to do that, and then your knowing how to teach your partners how to do that themselves. I'm happy to help you to an extent, if you want to pursue that route. 

No software will ever anticipate the needs of every user - thats why I designed PyCPT to be a set of python libraries and notebooks , meant to be modified and customized.

**Comment by kjhall01** [comment]
Also a warning, that these issue forums are fully public for all external partners to view freely.

**Comment by aaron-kaplan** [comment]
Bohar demoed using local data at the September 2023 training.
