### ISSUE TITLE
cross-year target season bug

### ISSUE THREAD

**Issue by awrobertson** [iri-pycpt/iri-pycpt.github.io#7]
Sometimes occurs when the time range of the forecast start date and target season cross January 1 (eg October 1 forecast start and JFM target season).

In attached NB, Oct 1 --> JFM fails in the MME with just the SPEAR model
ERROR:  The X file contains too many missing series
         /Users/andy/.pycpt_workspace/7176dfa8-0f23-4eb2-aacf-5d78bbff8659/original_predictor

[pycpt-operational- Benjy-mod.ipynb.zip](https://github.com/iri-pycpt/iri-pycpt.github.io/files/9990846/pycpt-operational-.Benjy-mod.ipynb.zip)

**Comment by awrobertson** [comment]
Solved in latest version of pycpt-operational-WAfrica.ipynb. Please test it out. 
ce.redate now uses yeardelta=48 to get around a problem with the year 2100 not being a leap year which caused the error to occur in xr.merge. Adding an error trap there would be a good idea, with the optional argument to check for compatibility compat=“broadcast_equals".
This fix might not be watertight for all training data setups in the future.
There is also an adjustment that increments the obs data period by 1 year. This was a silent error. Please test that too.

**Comment by awrobertson** [comment]
In fact, when both X and Y datasets are read, they are missing leap days:
Y = dl.download(dl.observations[predictand_name], dataDir / (predictand_name +'.tsv'), **download_args_obs, verbose=True, use_dlauth=False)

In cpt-dl/src/utilities:
ds = cio.open_cptdataset(path) if format == 'cptv10.tsv' else xr.open_dataset(path, decode_times=False)

THAT SEEMS TO BE A BUG in cio

Yet, when the hindcasts are read from the CCA output, it DOES have leap days and appears to work perfectly fine. Maybe CPT's .tsv time metadata is different from the DLs?

in cpt-core cca.py
    hcsts = open_cptdataset(str(cpt.outputs['hindcast_values'].absolute()) + '.txt' )

**Comment by awrobertson** [comment]
I tested the following edits to date time_timestamp_end(date):

def datetime_timestamp_end(date):
    if 'T' in date: 
        ymd, hms = date.split('T')
    else:
        ymd = date
    **yr = ymd.split('-')
    iyr = int(yr[0])**
    last_days = [None, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    **if (iyr-1900) % 4 == 0:
        last_days[2] = 29**
        print("leap year",iyr, last_days[2])
    
    fields = [int(i) for i in ymd.split('-')]
    while len(fields) < 3: 
        if len(fields) == 1: 
            fields.append(12)
        else:
            fields.append(last_days[fields[1]])
    return dt.datetime(*fields)

However, these only partly resolve the issue:
1) The original DJF issue arises in PFV because the hindcasts from the CCA output do have leap days, while the Y file do not. The latter is because datetime_timestamp_end doesn't provide them:
**download-->open_cptdataset-->read_cpt_date-->datetime_timestamp_end**
2) After "correcting" datetime_timestamp_end, all cptv10.tsv files created by PyCPT2 are now consistent: they all contain leap days.
3) BUT this causes the DJF season to have an additional day in leap years; thus the season length varies from year to year, which is REJECTED by CPT.
4) This solution is either: (a) to modify CPT so that it does not reject the files, or (b) to modify **to_cptv10** to not write Feb 29s. The latter requires a large number of modiications to  **to_cptv10**.

**Comment by awrobertson** [comment]
I discussed #4 in the previous comment with Simon on 01/05/23. He would prefer not to modify CPT because this error-trap (ie to ensure the target periods have equal length) is necessary to prevent other CPT users from erroneously setting up their predictanfd data with unequal lengths. He would prefer PyCPT to strip off the days information in the cptv10.tsv files, so that only the months are specified in the seasonal case, eg cpt:T=1982-12/1983-2 instead of cpt:T=1982-12-1/1983-2-28. I plan to discuss the feasibility of doing this with Aaron tomorrow.

My prelim assessment: 
In principle,  this could be done by inserting a switch for seasonal data, to control omitting the days info in the sesaysoanl case. (But we will still need daily T info in the subseasonal case, and I'm concerned that this same problem may simply occur there again, so this problem may resurface again in the sub-seasonal case.)

The way the PyCPT2 code is structured, adding the seasonal switch would mean making widespread changes throughout the [cptcore](https://github.com/iri-pycpt/cpt-core) module, in the cca, pcr, mlr, pfv, and deterministic skill functions, where “[to_cptv10](https://github.com/iri-pycpt/cpt-io/blob/main/src/fileio/cpt.py)” is called to write out the xarray variable in cptv10 format — as well as splitting "to_cptv10" into 2 sections, one for seasonal, one for subseasonal. For example in [cca.py](https://github.com/iri-pycpt/cpt-core/blob/main/src/functional/cca.py)

   # Load X dataset 
    to_cptv10(X, seasonal_switch, cpt.outputs['original_predictor'], row=x_lat_dim, col=x_lon_dim, T=x_sample_dim)
    cpt.write(1)

The cptcore, cptdl, and cptio modules are each published to [Anaconda](https://anaconda.org/iri-nextgen), and Kyle stressed to me that all changes to these core published libraries should be treated with the utmost care, with all changes being PR’d on git and published with a new version number. 

For testing purposes, I set up a version of the Notebook with all the relevant function copied into it from cptcore, cptdl, and cptio. I was able to experiment with it offline in that way, without having to touch the Anaconda modules.

I will ask Aaron for an estimate of the time it would take to implement this. If this is substantial, I will revisit with Simon since we are very short on Aaron's time for other urgent PyCPT2 work.

**Comment by awrobertson** [comment]
Discussed today with Aaron, Xandre & Bohar
- we noted that a similar issue could arise in the subseasonal case if the weekly predictand period ends on Feb 29, so fixing the seasonal case would not be enough
- Aaron proposed an simple solution for the seasonal case: create a monthly-data CHIRPS dataset [catalog entry](https://github.com/iri-pycpt/cpt-dl/blob/master/src/catalog.py). Aaron will test if this works. Please use [this notebook](https://github.com/iri-pycpt/notebooks/blob/master/Operations/pycpt-operational-WAfrica.ipynb) and set the predictand period to be DJF.

**Comment by awrobertson** [comment]
Simon commented:
- we noted that a similar issue could arise in the subseasonal case if the weekly predictand period ends on Feb 29, so fixing the seasonal case may not be enough
"What would pyCPT do in this case. It seems to me that you would always want the target period to be exactly the same number of days for sub-seasonal forecasts. I will need to check, but CPT should recognise that Feb 16 - 29 and Feb 16 - Mar 01 are the same as long as the second set of dates are not leap years. If CPT does not recognise that then I will definitely aim to fix it."

AWR: I think that would appear to take care of the sub-seasonal case.

**Comment by aaron-kaplan** [comment]
We had discussed the possibility of supporting dekadal forecasts, where the third dekad of February varies in length. If we can exclude that possibility then there isn't a problem.

**Comment by aaron-kaplan** [comment]
It turns out that the data we download from Ingrid are already in "months since 1960-01-01", because the Ingrid URL uses the seasonalAverage function. This dashes our hope that we could fix the problem for seasonal forecasts by changing the Ingrid URL. It must be cptio that converts the monthly date representation in the netcdf data to the daily representation in the tsv file.

My next thought is to modify cptio so that it generates yyyy-mm date representations for variables with monthly units, and yyyy-mm-dd for variables with daily units, instead of always using yyyy-mm-dd. Is anyone aware of a reason that wouldn't work? What notebooks should I test on the new code to verify that it doesn't break them?

**Comment by aaron-kaplan** [comment]
@awrobertson did you see my two previous comments?

**Comment by awrobertson** [comment]
Regarding the monthly data, you are right, I'd forgotten that seasonalAverage is used in the Ingrid URL. 

dl.download calls cio.open_cptdataset ==>  read_cpt_date ==> datetime_timestamp_end.
Kyle actually hardwired the latter without leap days, which would appear to solve the immediate problem.
However, this causes an incompatibility (see might previous comments from last December) bc when the hindcasts are read from the CCA output (via cio.to_cptv10), the DO have leap days.  

Is the solution to modify to_cptv10 so that it omits leap days, just like datetime_timestamp_end does??

**Comment by aaron-kaplan** [comment]
Hopefully fixed by https://github.com/iri-pycpt/cpt-io/pull/4.

**Comment by aaron-kaplan** [comment]
For the record, Simon says CPT has a special case for the last dekad of February such that its duration is allowed to vary from year to year. There isn't an analogous special case for seasons that end with February because users are meant to use the monthly representation for seasons instead of daily.

**Comment by aaron-kaplan** [comment]
Fixed in cpt-io 1.0.2, which I just published to conda-forge.
