### ISSUE TITLE
writing NextGen forecast files? adding that output to the parent directory

### ISSUE THREAD

**Issue by asherb18** [iri-pycpt/iri-pycpt.github.io#8]
Hi all
     When I have run PyCPT2 CCA forecasts for Niger I see the three folders (data, figures and output). The output are all netcdf files and are the forecast output. However, I only see the model by model output. There are no files for the NextGen/MME. It's critically important to have this output for a range of applications. 
       I've looked at the source code for CPT-core and CPT-IO, as well as the code in Andy's operational notebook. It seems that there is a mkdir command that refers to a switch for something called "Parents", which would seem to include specifications for the outputs. Can we add the MME/NextGen outputs to the Parents class?

**Comment by asherb18** [comment]
The output that is necessary for the FbF project is the forecast information and the hindcast information. It would be nice to also include skill scores in the FbF tool, but this is a lower priority. For version 1.9, the outputs are written as forecast_mu and forecast_var files. In PyCPT2, the model specific files are written in the following framework: 
CanSIPSIC3.PRCP_realtime_cca_forecasts.nc
CanSIPSIC3.PRCP_crossvalidate_cca_hindcasts.nc
We need the MME/NextGen versions of these files.

**Comment by awrobertson** [comment]
@asherb18 This is trivial for the forecast & hindcast mean:
# Write out the MME forecasts & hindcasts 
det_fcst.to_netcdf(outputDir /  ('MME_deterministic_forecasts.nc'))
det_hcst.to_netcdf(outputDir /  ('MME_deterministic_hindcasts.nc'))

But the error variance:
pev_hcst.to_netcdf(outputDir /  ('MME_hindcast_prediction_error_variance.nc'))
will need to be transformed if a y-transform was applied. I am looking into that.

**Comment by asherb18** [comment]
Thanks very much Andy. Best,

**Comment by awrobertson** [comment]
@asherb18, Asher: Remi told me today that the FbF maprooms only use the 3 above files, together with the original Y file. Ingrid is used to compute the forecast variance in the case that a y-transform was applied. So I think you already have all that you need to use PyCPT2 for FbF?

**Comment by asherb18** [comment]
OK - for the forecast variance. But did you update the source code to write the MME hindcast and forecast values?

**Comment by awrobertson** [comment]
@asherb18 Asher: you just need to insert a cell before "Plot MME Forecast Skill", with those 3 lines
det_fcst.to_netcdf(outputDir / ('MME_deterministic_forecasts.nc'))
det_hcst.to_netcdf(outputDir / ('MME_deterministic_hindcasts.nc'))
pev_hcst.to_netcdf(outputDir / ('MME_hindcast_prediction_error_variance.nc'))

LMK if there's any problem.

**Comment by awrobertson** [comment]
Added writing of MME output files to the WAfrica demo notebook.
